// <auto-generated />
namespace Koleg.io.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UploadSubjectYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadSubjectYear));
        
        string IMigrationMetadata.Id
        {
            get { return "202401131248122_UploadSubjectYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
